export const CREATE_RESTAURANT = 'CREATE_RESTAURANT';
export const STOP_CREATING = 'STOP_CREATING';
export const CHANGE_TAB = 'CHANGE_TAB';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const CANCEL_DELETE = 'CANCEL_DELETE';
